export const orderStatus = {
  NEW: 'NEW',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  PREPARING: 'PREPARING',
  SERVING: 'SERVING',
  DINING: 'DINING',
  BILL_REQUESTED: 'BILL_REQUESTED',
  BILLED: 'BILLED',
  COMPLETED: 'COMPLETED'
};
